name: Release
on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      SSH_KNOWN_HOSTS:
        required: true
      SSH_USERNAME:
        required: true
      SERVER_IP:
        required: true
      DOWNLOADS_DIR:
        required: true
      THEME_DIR:
        required: true
jobs:
  release:
    name: Release .zip
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create zip and upload
        run: |
          name=$(basename -s .git $(git config --get remote.origin.url))
          git archive -o $name.zip --prefix=$name/ HEAD
          rsync -e "ssh -o StrictHostKeyChecking=no" $name.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.DOWNLOADS_DIR }}
      - name: Upload to demo
        run: rsync -razhe "ssh -o StrictHostKeyChecking=no" --exclude={'.git','.github','.gitignore','composer.json'} . ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.THEME_DIR }}